// H'ash Bistro — menu extracted from flyer PDF (prices best-effort where PDF text order was ambiguous)
window.HASH_MENU = {
  currency: "lei",
  categories: [
    { id: "meniul-zilei", name: "Meniul Zilei", note: "Fel principal 180–220g + garnitură + salată + pâine. Adaugă o ciorbă 350ml la doar 8 lei." },
    { id: "meniuri-speciale", name: "Meniuri Speciale" },
    { id: "supe-ciorbe", name: "Supe & Ciorbe" },
    { id: "salate", name: "Salate Aperitiv" },
    { id: "peste", name: "Pește" },
    { id: "traditionale", name: "Mâncare Tradițională" },
    { id: "paste", name: "Paste" },
    { id: "la-tigaie", name: "La Tigaie" },
    { id: "gratar", name: "Grătar" },
    { id: "garnituri", name: "Garnituri" },
    { id: "salate-insotire", name: "Salate de Însoțire" },
    { id: "platouri", name: "Platouri" },
    { id: "pizza", name: "Pizza 32 cm" },
    { id: "burgers", name: "Burgeri" },
    { id: "desert", name: "Desert" }
  ],
  products: [
    { id: "mz", cat: "meniul-zilei", name: "Meniul Zilei", price: 30, w: "180–220g + garnitură + salată",
      desc: "Alege felul principal, garnitura și salata. Pâine/chiflă inclusă.",
      options: {
        main: ["Aripioare la ceaun","Cârnați speciali","Ceafă","Chifteluțe de pui (marinate sau simple)","Frigărui pui cu legume","Mici 3 buc.","Mușchi file de porc","Ostropel de pui","Piept de pui la grătar","Pui Shanghai","Pulpă de pui la cuptor","Pulpă dezosată la grătar","Șnițel de porc","Șnițel de pui","Șnițel pui „California”","Strips piept de pui"],
        side: ["Cartofi prăjiți","Piure","Cartofi nature","Cartofi țărănești","Orez libanez","Orez cu legume","Orez cu ciuperci","Mămăligă"],
        salad: ["Varză albă","Varză murată","Murături asortate","Salată de vară"],
        extra: { name: "Adaugă o ciorbă 350ml", price: 8 }
      } },
    { id: "sp1", cat: "meniuri-speciale", name: "Pui Sweet Chilly + orez basmati", price: 38, w: "100g/150g/150g", desc: "Piept de pui, morcov, sos sweet chilly, orez basmati", spicy: true },
    { id: "sp2", cat: "meniuri-speciale", name: "Pui Curry cu orez basmati", price: 38, w: "100g/150g/150g", desc: "Piept de pui, ceapă, condimente, orez basmati" },
    { id: "sp3", cat: "meniuri-speciale", name: "Shaorma pui la farfurie", price: 35, w: "180g/100g/150g", desc: "Carne pui, cartofi prăjiți, salată de varză, ceapă, castraveți murați, maioneză, sos iaurt cu curry" },
    { id: "sp4", cat: "meniuri-speciale", name: "Shaorma de vită", price: 42, w: "180g/100g/150g", desc: "Carne vită, cartofi prăjiți, salată de varză, ceapă, castraveți murați, sos Anatolia" },
    { id: "sp5", cat: "meniuri-speciale", name: "Pastramă de oaie cu mămăligă și usturoi", price: 49, w: "180g/200g/50g", desc: "Pastramă de oaie, mămăligă, mujdei de usturoi" },
    // tbd: preț și gramaj de confirmat cu bistroul — descriere scrisă după fotografie
    { id: "sp6", cat: "meniuri-speciale", name: "Cheesy Bacon Fried", price: 32, w: "350g", desc: "Cartofi prăjiți, sos cheddar, cuburi de bacon și șuncă, două ouă ochiuri, boia", tbd: true },
    { id: "sp7", cat: "meniuri-speciale", name: "Pui Shanghai", price: 36, w: "250g/50g", desc: "Fâșii de pui în crustă crocantă, sos Shanghai cremos, ceapă verde, ardei iute", tbd: true },
    { id: "sc1", cat: "supe-ciorbe", name: "Supă de pui cu găluște", price: 18, w: "400g/100g" },
    { id: "sc2", cat: "supe-ciorbe", name: "Supă cremă de legume", price: 18, w: "400g" },
    { id: "sc3", cat: "supe-ciorbe", name: "Ciorbă de burtă", price: 20, w: "80g/400g" },
    { id: "sc4", cat: "supe-ciorbe", name: "Ciorbă de văcuță", price: 18, w: "80g/400g" },
    { id: "sc5", cat: "supe-ciorbe", name: "Ciorbă de pui à la grec", price: 18, w: "80g/400g" },
    { id: "sc6", cat: "supe-ciorbe", name: "Ciorbă de perișoare (de pui)", price: 18, w: "400g/80g" },
    { id: "sc7", cat: "supe-ciorbe", name: "Fasole cu afumătură", price: 18, w: "430g/50g" },
    { id: "sc8", cat: "supe-ciorbe", name: "Ciorbă de cartofi și afumătură", price: 18, w: "400g/80g" },
    { id: "sc9", cat: "supe-ciorbe", name: "Ciorbă de fasole de post", price: 15, w: "480g", post: true },
    { id: "sc10", cat: "supe-ciorbe", name: "Ciorbă de legume de post", price: 15, w: "480g", post: true },
    { id: "sa1", cat: "salate", name: "Salată Bulgărească", price: 32, w: "400–500g + chiflă", desc: "Salată iceberg, roșii, castraveți, ardei gras, șuncă, măsline, brânză, ou" },
    { id: "sa2", cat: "salate", name: "Salată Caesar", price: 35, w: "400g + chiflă", desc: "Salată iceberg, roșii, castraveți, ardei gras, măsline, piept de pui, sos caesar" },
    { id: "sa3", cat: "salate", name: "Salată Con Tonno", price: 32, w: "400g + chiflă", desc: "Salată iceberg, roșii, ardei gras, măsline, porumb dulce, ton, lămâie" },
    { id: "sa4", cat: "salate", name: "Salată crispy de pui", price: 30, w: "400g + chiflă", desc: "Salată iceberg, roșii, castraveți, ardei gras, măsline, piept de pui crispy, dressing" },
    { id: "sa5", cat: "salate", name: "Salată Somon Fumé", price: 38, w: "400g + chiflă", desc: "Somon fumé, castraveți, salată iceberg, roșii, ardei gras, parmezan, porumb dulce, lămâie" },
    { id: "pe1", cat: "peste", name: "Somon file", price: 55, w: "220g + orez basmati 150g + lămâie", desc: "File de somon la grătar, orez basmati, lămâie" },
    { id: "pe2", cat: "peste", name: "Păstrăv la grătar", price: 42, w: "250g + cartofi natur 150g + lămâie", desc: "Păstrăv întreg la grătar, cartofi natur, lămâie" },
    { id: "pe3", cat: "peste", name: "Hamsii cu mămăligă și usturoi", price: 25, w: "150g/180g/50g", desc: "Hamsii prăjite, mămăligă, mujdei" },
    { id: "pe4", cat: "peste", name: "Creveți în sos de vin", price: 52, w: "250g", desc: "Creveți întregi în sos de vin alb, ardei gras, verdeață", tbd: true },
    { id: "tr1", cat: "traditionale", name: "Carcalete", price: 44, w: "150g/150g/50g/50g", desc: "Cartofi prăjiți, ceafă porc, ou, telemea de vacă, unt" },
    { id: "tr2", cat: "traditionale", name: "Ciulama de pui cu ciuperci + mămăligă", price: 28, w: "250g/250g", desc: "Pui, ciuperci, stock de pui, smântână de gătit, unt, făină, condimente" },
    { id: "tr3", cat: "traditionale", name: "Iahnie cu cârnați și salată de murături", price: 28, w: "300g/100g/100g" },
    { id: "tr4", cat: "traditionale", name: "Mămăligă cu brânză și smântână", price: 22, w: "200g/80g/80g" },
    { id: "tr5", cat: "traditionale", name: "Mazăre / Iahnie fasole / Spanac", price: 20, w: "300g", post: true },
    { id: "tr6", cat: "traditionale", name: "Mazăre cu piept de pui / aripioare", price: 25, w: "200g/100g" },
    { id: "tr7", cat: "traditionale", name: "Pomana porcului + mămăligă", price: 35, w: "250g/200g" },
    { id: "tr8", cat: "traditionale", name: "Saramură de pui cu mămăligă", price: 28, w: "250g/200g" },
    { id: "tr9", cat: "traditionale", name: "Sarmale cu carne în foi de varză cu mămăligă", price: 30, w: "4 buc · 200g/200g" },
    { id: "tr10", cat: "traditionale", name: "Sarmale tradiționale de post cu mămăligă", price: 24, w: "4 buc · 200g/200g", post: true },
    { id: "tr11", cat: "traditionale", name: "Tocăniță de cartofi cu ciuperci", price: 22, w: "300g", post: true },
    { id: "tr12", cat: "traditionale", name: "Tochitură dobrogeană cu mămăligă", price: 38, w: "250/200/50/50g" },
    { id: "tr13", cat: "traditionale", name: "Varză călită cu cârnăciori și mămăligă", price: 28, w: "200g/100g/200g" },
    { id: "tr14", cat: "traditionale", name: "Carne la garniță cu mămăligă și usturoi", price: 42, w: "300g/200g/50g", desc: "Carne de porc la garniță, cârnați, costiță afumată, mămăligă, mujdei de usturoi", tbd: true },
    { id: "tr15", cat: "traditionale", name: "Coaste de pui cu sos picant", price: 38, w: "300g/200g", desc: "Carne afumată tocată cu cârnați și costiță, mămăligă, mujdei de usturoi", spicy: true, tbd: true },
    { id: "pa1", cat: "paste", name: "Paste Amatriciana", price: 30, w: "350g", desc: "Paste grana duro, sos de roșii, bacon, usturoi, busuioc, parmezan, ulei de măsline" },
    { id: "pa2", cat: "paste", name: "Paste Bolognese", price: 35, w: "350g", desc: "Paste grana duro, sos de roșii, carne vită, sos ragù, busuioc, parmezan, ulei de măsline" },
    { id: "pa3", cat: "paste", name: "Paste Carbonara", price: 30, w: "350g", desc: "Paste grana duro, smântână de gătit, ouă, bacon, usturoi, busuioc, parmezan" },
    { id: "pa4", cat: "paste", name: "Paste cu ton", price: 30, w: "350g", desc: "Paste grana duro, ton, roșii, porumb, ceapă, capere, usturoi, busuioc, parmezan" },
    { id: "pa5", cat: "paste", name: "Paste Milanese", price: 30, w: "350g", desc: "Paste grana duro, sos de roșii, șuncă, ciuperci, usturoi, busuioc, parmezan" },
    { id: "pa6", cat: "paste", name: "Paste Quattro Formaggi", price: 35, w: "350g", desc: "Paste grana duro, smântână de gătit, gorgonzola, mozzarella, cașcaval afumat, brie, parmezan" },
    { id: "pa7", cat: "paste", name: "Paste Siciliene", price: 30, w: "350g", desc: "Paste grana duro, sos de roșii, piept de pui, măsline, ciuperci, usturoi, busuioc, parmezan" },
    { id: "pa8", cat: "paste", name: "Tagliatele cu fructe de mare", price: 45, w: "400g", desc: "Tagliatele, creveți, fructe de mare, sos alb cremos, parmezan", tbd: true },
    { id: "ti1", cat: "la-tigaie", name: "Ficăței în sos de vin", price: 22, w: "250g/300g", desc: "Ficăței de pasăre, unt, vin alb, sare, piper" },
    { id: "ti2", cat: "la-tigaie", name: "Ficăței Lionezi", price: 24, w: "250g/300g", desc: "Ficăței de pasăre, ceapă, unt, vin alb, sare, piper" },
    { id: "ti3", cat: "la-tigaie", name: "Tigaie de pui, porc sau mix", price: 32, w: "100g/200g", desc: "Normală sau picantă — ceapă, ardei gras, morcov, țelină, ciuperci, usturoi, vin alb", spicyOpt: true },
    { id: "ti4", cat: "la-tigaie", name: "Piept de pui cu sos gorgonzola", price: 35, w: "180g/150g", desc: "Piept de pui, brânză gorgonzola, unt, smântână de gătit, condimente" },
    { id: "ti5", cat: "la-tigaie", name: "Tigaie de vită cu sos de rodie", price: 47, w: "180g/150g", desc: "Vită, ceapă, ardei gras, sos de rodie, condimente" },
    { id: "ti6", cat: "la-tigaie", name: "Wok de pui", price: 28, w: "350g", desc: "Piept de pui, ceapă, morcov, țelină, ciuperci, usturoi, ghimbir, ulei de susan, sos soia, susan" },
    { id: "ti7", cat: "la-tigaie", name: "Noodles cu legume", price: 35, w: "350g", desc: "Tăiței, ceapă, morcov, țelină, ciuperci, usturoi, ghimbir, ulei de susan, sos soia", post: true },
    { id: "ti8", cat: "la-tigaie", name: "Noodles pui cu legume", price: 38, w: "350g", desc: "Paste făinoase, piept de pui, ceapă, morcov, țelină, ciuperci, usturoi, ghimbir, sos soia" },
    { id: "ti9", cat: "la-tigaie", name: "Tigaie grecească", price: 35, w: "300g/150g", desc: "Fâșii de porc, ardei gras roșu și galben, roșii cherry, ceapă roșie, telemea rasă, pită", tbd: true },
    { id: "gr1", cat: "gratar", name: "Ceafă de porc", price: 25, w: "220g" },
    { id: "gr2", cat: "gratar", name: "Frigărui de pui cu legume", price: 22, w: "250g · 2 buc" },
    { id: "gr3", cat: "gratar", name: "Mici porc", price: 6, w: "60g / buc" },
    { id: "gr4", cat: "gratar", name: "Mușchi file / Cotlet de porc", price: 25, w: "200g / 250g" },
    { id: "gr5", cat: "gratar", name: "Piept de pui", price: 18, w: "180g" },
    { id: "gr6", cat: "gratar", name: "Pulpă dezosată", price: 18, w: "180g" },
    { id: "gr7", cat: "gratar", name: "Scăricică / fleică de porc", price: 25, w: "200g" },
    { id: "gr8", cat: "gratar", name: "Piept pui cu ou și cheddar", price: 39, w: "180g/50g/50g" },
    { id: "gr9", cat: "gratar", name: "Cotlet de berbecuț", price: 51, w: "300g · 3–4 buc" },
    { id: "gr10", cat: "gratar", name: "Mușchi de vită", price: 58, w: "220g + cartofi + sos", desc: "Mușchi de vită la grătar, cartofi prăjiți, unt de ierburi, lămâie, sos de usturoi", tbd: true },
    { id: "gr11", cat: "gratar", name: "Coastă de porc cu sos barbecue", price: 55, w: "500g + garnitură", desc: "Coastă de porc glazurată cu sos barbecue, piure, cartofi prăjiți", tbd: true },
    { id: "ga1", cat: "garnituri", name: "Cartofi nature", price: 8, w: "200g" },
    { id: "ga2", cat: "garnituri", name: "Cartofi prăjiți", price: 8, w: "200g" },
    { id: "ga3", cat: "garnituri", name: "Cartofi rustici", price: 13, w: "200g" },
    { id: "ga4", cat: "garnituri", name: "Mămăligă", price: 8, w: "200g" },
    { id: "ga5", cat: "garnituri", name: "Orez basmati cu legume", price: 15, w: "200g" },
    { id: "ga6", cat: "garnituri", name: "Piure de cartofi", price: 13, w: "200g" },
    { id: "si1", cat: "salate-insotire", name: "Castraveți verzi", price: 10, w: "200g", desc: "Castraveți verzi, oțet, ulei, mărar, sare" },
    { id: "si2", cat: "salate-insotire", name: "Murături asortate", price: 10, w: "200g", desc: "Varză murată, gogonele, gogoșar, castravete murat" },
    { id: "si3", cat: "salate-insotire", name: "Roșii", price: 10, w: "200g" },
    { id: "si4", cat: "salate-insotire", name: "Salată de vară", price: 10, w: "200g", desc: "Roșii, castraveți, ceapă, ardei gras, iceberg" },
    { id: "si5", cat: "salate-insotire", name: "Varză albă", price: 10, w: "200g" },
    { id: "si6", cat: "salate-insotire", name: "Varză murată", price: 10, w: "200g" },
    { id: "pl1", cat: "platouri", name: "Platou cald", price: 240, w: "4–6 pers.", desc: "Mici 6 buc, cârnați extra 6 buc, Shanghai (gujon) 14 buc, chifteluțe de pui 12 buc, cașcaval pane 6 buc, cartofi prăjiți 6 porții, murături 6 porții, chifle, muștar. Tacâmuri incluse." },
    { id: "pl2", cat: "platouri", name: "Platou mix grill", price: 300, w: "4–6 pers.", desc: "Ceafă 6 buc, piept de pui 6 buc, frigărui pui 6 buc, mici 6 buc, cartofi prăjiți 6 porții, murături 6 porții, chifle, muștar. Tacâmuri incluse." },
    { id: "pl3", cat: "platouri", name: "Bruschete", price: 38, w: "6 buc.", desc: "Felii de baghetă prăjite, roșii, mozzarella, prosciutto, măsline, busuioc", tbd: true },
    { id: "pz1", cat: "pizza", name: "Pizza Margherita", price: 32, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, busuioc" },
    { id: "pz2", cat: "pizza", name: "Pizza Capriciosa", price: 39, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, șuncă, ciuperci, măsline" },
    { id: "pz3", cat: "pizza", name: "Pizza Carbonara", price: 43, w: "32 cm", desc: "Blat pizza, sos alb, mozzarella, șuncă, parmezan, ou, usturoi" },
    { id: "pz4", cat: "pizza", name: "Pizza Carnivora", price: 43, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, salam chorizo, salam picant, bacon, piept de pui, cârnăciori" },
    { id: "pz5", cat: "pizza", name: "Pizza H'ash", price: 45, w: "32 cm", desc: "Blat pizza, salam, cârnăciori, ciuperci, măsline, ardei gras, porumb, ceapă, prosciutto", star: true },
    { id: "pz6", cat: "pizza", name: "Pizza Diavola", price: 37, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, salam picant, ardei iute", spicy: true },
    { id: "pz7", cat: "pizza", name: "Pizza Funghi", price: 35, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, ciuperci, oregano" },
    { id: "pz8", cat: "pizza", name: "Pizza Hawai", price: 38, w: "32 cm", desc: "Blat pizza, sos de roșii, șuncă, mozzarella, ananas, porumb" },
    { id: "pz9", cat: "pizza", name: "Pizza Polo e Funghi", price: 39, w: "32 cm", desc: "Blat pizza, sos de roșii, șuncă, mozzarella, piept de pui, ciuperci, porumb" },
    { id: "pz10", cat: "pizza", name: "Pizza Prosciutto Funghi", price: 37, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, șuncă, ciuperci" },
    { id: "pz11", cat: "pizza", name: "Pizza per Bambini", price: 36, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, șuncă, porumb" },
    { id: "pz12", cat: "pizza", name: "Pizza Quattro Stagioni", price: 39, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, șuncă, salam, ciuperci, măsline" },
    { id: "pz13", cat: "pizza", name: "Pizza Quattro Formaggi", price: 42, w: "32 cm", desc: "Blat pizza, sos alb, mozzarella, cașcaval afumat, gorgonzola, parmezan" },
    { id: "pz14", cat: "pizza", name: "Pizza Tonno", price: 39, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, ton, ceapă, capere, porumb" },
    { id: "pz15", cat: "pizza", name: "Pizza Summer", price: 39, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, dovlecei, roșii cherry, ciuperci, porumb, ceapă, ardei gras, măsline" },
    { id: "pz16", cat: "pizza", name: "Pizza Nordica", price: 45, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, lămâie, capere, ceapă, smântână, somon afumat" },
    { id: "pz17", cat: "pizza", name: "Pizza Crispy", price: 43, w: "32 cm", desc: "Blat pizza, sos de roșii, mozzarella, ardei gras, strips crispy de pui, cartofi prăjiți, sos cheddar", tbd: true },
    { id: "bg1", cat: "burgers", name: "Burger H'ash", price: 40, w: "400g + cartofi 80g", desc: "Chiflă, vită Black Angus, cheddar, salată, ceapă caramelizată, castravete murat, bacon, sos H'ash", star: true },
    { id: "bg2", cat: "burgers", name: "Burger Chicken H'ash", price: 38, w: "400g + cartofi 80g", desc: "Chiflă, crispy piept pui, cheddar, salată, castravete murat, ceapă caramelizată, bacon, sos H'ash" },
    { id: "bg3", cat: "burgers", name: "Burger Clasic", price: 32, w: "400g + cartofi 80g", desc: "Chiflă, vită Black Angus, roșie, salată, ceapă roșie, castravete murat, sos H'ash" },
    { id: "bg4", cat: "burgers", name: "Dublu Cheeseburger", price: 59, w: "550g + cartofi 80g", desc: "Chiflă, 2× vită Black Angus, ceapă roșie, salată, cheddar, castravete murat, ceapă caramelizată, sos H'ash" },
    { id: "de1", cat: "desert", name: "Clătite cu dulceață", price: 18, w: "250g", desc: "Vișine sau afine" },
    { id: "de2", cat: "desert", name: "Clătite cu Nutella", price: 20, w: "250g" },
    { id: "de3", cat: "desert", name: "Clătite Nutella, banane și nucă", price: 25, w: "350g" },
    { id: "de4", cat: "desert", name: "Papanași cu ciocolată Nutella", price: 25, w: "250g/80g/50g" },
    { id: "de5", cat: "desert", name: "Papanași cu smântână și dulceață de afine", price: 25, w: "250g/80g/50g" }
  ],
  extras: {
    pizzaToppings: [
      { name: "Extra topping legume", price: 5, desc: "Mozzarella, ardei, măsline, ciuperci, porumb, ananas, ceapă, roșii" },
      { name: "Extra topping carne", price: 5, desc: "Șuncă, bacon, cârnați, ton, salam, parmezan, piept pui" },
      { name: "Sosuri", price: 3, desc: "Dulce / picant / Glen / smântână" },
      { name: "Ardei iute", price: 2 }
    ]
  }
};
